FORMAT: 1A
HOST: https://localhost:3000

# linguico-api

Polls is a simple API allowing consumers to view polls and vote in them.

###### You will need an Auth token to be able to access students, appointments and teachers


## Students Collection [/api/v1/students/]

### List All Students [GET]
Retrieve a list of students

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "marvellous",
                "email": "marvellous@gmail.com",
                "password_digest": "$2a$12$gKlxCv/RcUynJk0h4ct6VexDQ4LqtL2kbYI506L97W60BU1gsUd56",
                "bio": null,
                "languages": "{:english=>true, :french=>true}",
                "nationality": "nigeria",
                "created_at": "2020-09-04T17:21:50.262Z",
                "updated_at": "2020-09-04T17:21:50.262Z"
            },
            {
                "id": 2,
                "name": "iyke",
                "email": "iyke@gmail.com",
                "password_digest": "$2a$12$e9GIMdtZYb8cfgLiaJpLnucfHvtFeTKV5TWQxRwEjIYcWuw.yVIWG",
                "bio": null,
                "languages": null,
                "nationality": null,
                "created_at": "2020-09-04T18:21:04.091Z",
                "updated_at": "2020-09-04T18:21:04.091Z"
            },
            {
                "id": 5,
                "name": "ifeoma",
                "email": "ifeoma@gmail.com",
                "password_digest": "$2a$12$m7D1ve2Pi8CqqF0DhWz1FeMbVig7bB0.cDxmdt6LjqHGzU.peGfuW",
                "bio": null,
                "languages": "{:english=>true,:yoruba=>true}",
                "nationality": "canada",
                "created_at": "2020-09-04T18:32:55.853Z",
                "updated_at": "2020-09-04T18:32:55.853Z"
            }
        ]

### Create a New Student [POST]

You may create your own student using this action. It takes a JSON
object containing the student and other parameters such as their name, email, nationality and more.

+ Request (application/json)

        {
            "name": "ifeoma",
            "email": "ifeoma@gmail.com",
            "password_digest": "$2a$12$m7D1ve2Pi8CqqF0DhWz1FeMbVig7bB0.cDxmdt6LjqHGzU.peGfuW",
            "bio": null,
            "languages": "{:english=>true,:yoruba=>true}",
            "nationality": "canada",
        }

+ Response 201 (application/json)

    + Headers


    + Body

            {
                "id": 5,
                "name": "ifeoma",
                "email": "ifeoma@gmail.com",
                "password_digest": "$2a$12$m7D1ve2Pi8CqqF0DhWz1FeMbVig7bB0.cDxmdt6LjqHGzU.peGfuW",
                "bio": null,
                "languages": "{:english=>true,:yoruba=>true}",
                "nationality": "canada",
                "created_at": "2020-09-04T18:32:55.853Z",
                "updated_at": "2020-09-04T18:32:55.853Z"
            }
            
            
## Student [/api/v1/students/id/]

### Retrieve a Student [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "marvellous",
                "email": "marvellous@gmail.com",
                "password_digest": "$2a$12$gKlxCv/RcUynJk0h4ct6VexDQ4LqtL2kbYI506L97W60BU1gsUd56",
                "bio": null,
                "languages": "{:english=>true, :french=>true}",
                "nationality": "nigeria",
                "created_at": "2020-09-04T17:21:50.262Z",
                "updated_at": "2020-09-04T17:21:50.262Z"
            }
        ]

### Update a Student details [PATCH]

+ Request (application/json)

        {
            "name": "jonahifeoma",
            "email": "ifeoma@gmail.com",
            "password_digest": "$2a$12$m7D1ve2Pi8CqqF0DhWz1FeMbVig7bB0.cDxmdt6LjqHGzU.peGfuW",
            "bio": null,
            "languages": "{:english=>true,:yoruba=>true}",
            "nationality": "canada",
        }

+ Response 201 (application/json)

    + Body

            1
           
### Delete a Student details [DELETE]

+ Request (application/json)


+ Response 201 (application/json)

    + Body

            1

## Appointments Collection [/api/v1/appointments/]

### Get appointments [GET]

+ Response 200 (application/json)

    [
    {
        "id": 1,
        "desc": "To Speak french on italki",
        "appointment_time": "2020-09-20T22:00:00.000Z",
        "appointment_date": "2020-09-20T00:00:00.000Z",
        "student_id": 1,
        "teacher_id": 1,
        "created_at": "2020-09-04T23:55:13.591Z",
        "updated_at": "2020-09-04T23:55:13.591Z"
    },
    {
        "id": 2,
        "desc": "Meeting with Spanish Layla",
        "appointment_time": "2020-09-20T22:00:00.000Z",
        "appointment_date": "2020-09-20T00:00:00.000Z",
        "student_id": 1,
        "teacher_id": 1,
        "created_at": "2020-09-06T21:07:30.772Z",
        "updated_at": "2020-09-06T21:07:30.772Z"
    },
    {
        "id": 3,
        "desc": "Meeting with Chinese Yang",
        "appointment_time": "2020-09-20T22:00:00.000Z",
        "appointment_date": "2020-09-20T00:00:00.000Z",
        "student_id": 1,
        "teacher_id": 1,
        "created_at": "2020-09-06T21:07:49.932Z",
        "updated_at": "2020-09-06T21:07:49.932Z"
    }
]

### Create a New Appointment [POST]

+ Request (application/json)

        {
            "desc": "Learning English with Maruiki",
            "appointment_date": "2020-09-20T22:00:00.000Z",
            "appointment_time": "2020-09-20T22:00:00.000Z",
            "teacher_id": "1"
        }

+ Response 201 (application/json)

    + Body

            {
                "id": 4,
                "desc": "Learning English with Maruiki",
                "appointment_time": "2020-09-20T22:00:00.000Z",
                "appointment_date": "2020-09-20T22:00:00.000Z",
                "student_id": 3,
                "teacher_id": 1,
                "created_at": "2020-09-06T21:37:19.094Z",
                "updated_at": "2020-09-06T21:37:19.094Z"
            }

## Appointment [/api/v1/appointments/id]

### Get single appointment [GET]

+ Response 200 (application/json)

    [
    {
        "id": 1,
        "desc": "To Speak french on italki",
        "appointment_time": "2020-09-20T22:00:00.000Z",
        "appointment_date": "2020-09-20T00:00:00.000Z",
        "student_id": 1,
        "teacher_id": 1,
        "created_at": "2020-09-04T23:55:13.591Z",
        "updated_at": "2020-09-04T23:55:13.591Z"
    },
]

### Update a New Appointment [POST]

+ Request (application/json)

        {
            "desc": "Learning English with Simbi",
        }

+ Response 201 (application/json)

    + Body

            {
                "id": 4,
                "desc": "Learning English with Maruiki",
                "appointment_time": "2020-09-20T22:00:00.000Z",
                "appointment_date": "2020-09-20T22:00:00.000Z",
                "student_id": 3,
                "teacher_id": 1,
                "created_at": "2020-09-06T21:37:19.094Z",
                "updated_at": "2020-09-06T21:37:19.094Z"
            }
            
### Delete an Appointment [DELETE]

+ Request (application/json)


+ Response 201 (application/json)

    + Body
    

## Teachers Collection [/api/v1/teachers/]

### Get teachers [GET]

+ Response 200 (application/json)

    [
        {
            "id": 1,
            "name": "tunde",
            "email": "tunde@gmail.com",
            "password": "floboo",
            "bio": null,
            "languages": "{:english=>true, :french=>true}",
            "nationality": "france",
            "created_at": "2020-09-04T23:54:02.645Z",
            "updated_at": "2020-09-04T23:54:02.645Z"
        }
    ]
    

### Create a New Teacher [POST]

+ Request (application/json)

        {
            "name": "maria",
            "email": "maria@gmail.com",
            "password": "floboo",
            "bio": null,
            "languages": "{:english=>true, :french=>true}",
            "nationality": "brazil"
        }

+ Response 201 (application/json)

    + Body

            {
                "id": 2,
                "name": "maria",
                "email": "maria@gmail.com",
                "password_digest": "floboo",
                "bio": null,
                "languages": "{:english=>true, :french=>true}",
                "nationality": "brazil",
                "created_at": "2020-09-04T23:54:02.645Z",
                "updated_at": "2020-09-04T23:54:02.645Z"
            }

## Teacher [/api/v1/teachers/id]

### Get single teacher [GET]

+ Response 200 (application/json)

    [
       {
                "id": 1,
                "name": "tunde",
                "email": "tunde@gmail.com",
                "password": "floboo",
                "bio": null,
                "languages": "{:english=>true, :french=>true}",
                "nationality": "france",
                "created_at": "2020-09-04T23:54:02.645Z",
                "updated_at": "2020-09-04T23:54:02.645Z"
        }
    ]

### Update a Teacher [POST]

+ Request (application/json)

        {
            "name": "Funa",
        }

+ Response 201 (application/json)

    + Body

             {
                "id": 2,
                "name": "funa",
                "email": "maria@gmail.com",
                "password_digest": "floboo",
                "bio": null,
                "languages": "{:english=>true, :french=>true}",
                "nationality": "brazil",
                "created_at": "2020-09-04T23:54:02.645Z",
                "updated_at": "2020-09-04T23:54:02.645Z"
            }
            
### Delete an Appointment [DELETE]

+ Request (application/json)


+ Response 201 (application/json)

    + Body


